# Build ASP.NET Core project using Azure Pipelines
# Documentation: https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# Définition de l'image VM pour l'exécution du pipeline
pool:
  name: SH1  # Remplacez SH1 par le bon nom si nécessaire

# Définition des variables utilisées dans le pipeline
variables:
  nodeVersion: 'v23.9.0'
  projectFolder: 'src/angular'
  buildOutputFolder: 'src/angular/dist/angular'

# Étapes de la construction
steps:

# Installation de Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# Installation des dépendances et build du projet Angular
- script: |
    cd $(projectFolder)
    npm install
    npm run build
  displayName: 'Install dependencies and build Angular project'

# Copie des fichiers générés vers le dossier de staging
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(buildOutputFolder)' 
    contents: '**/*' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
  displayName: 'Copy built files to staging directory'

# Archivage des fichiers en un fichier ZIP
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    includeRootFolder: false
  displayName: 'Archive files into a ZIP package'

# Publication de l'archive en tant qu'artifact de build
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Publish the build artifact'
