
trigger:
- master 
- develop
- main

# Définition de l'image VM pour l'exécution du pipeline
pool:
  name: SH1  # Remplacez SH1 par le bon nom si nécessaire

# Définition des variables utilisées dans le pipeline
variables:
  nodeVersion: 'v23.9.0'
  projectFolder: 'src/angular'
  buildOutputFolder: 'src/angular/dist/angular'
  developmentBranchName: 'develop'    
  masterBranchName: 'master'

# Étapes de la construction
steps:
# Installation de Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  

# Archivage des fichiers en un fichier ZIP
- task: CopyFiles@2
  displayName: 'Copy Files to: dist'
  inputs:
        SourceFolder: dist
        Contents: '**/**'
        TargetFolder: 'src/dist'

# Publication de l'archive en tant qu'artifact de build
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Publish the build artifact'

# Publication des artefacts finaux
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'dist'
    pathtoPublish: 'dist'
  displayName: 'Publish Artifacts'

